# deploy.yml
# - Assumes you have run bootstrap.yml to install pre-requists.

- hosts: api
  gather_facts: no
  roles:
    # - apt-update
    - landexplorer-api

- hosts: api:&production
  gather_facts: no
  roles:
    - landexplorer-api-letsencrypt
